sources:
  - Jacquard24Charted.glyphs
familyName: Jacquard 24 Charted
buildOTF: false
autohintTTF: false
decomposeTransformedComponents: true
flattenComponents: true
extraFontmakeArgs: --filter "ufo2ft.filters.decomposeComponents::DecomposeComponentsFilter"